/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { SurfRental } from "./SurfRental";
export * as factories from "./factories";
export { SurfRental__factory } from "./factories/SurfRental__factory";
